version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db

  db:
    restart: always
    build: db/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roytuts
      MYSQL_USER: root 
    volumes: 
      - ./db/data/:/var/lib/mysql:rw
