version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  #  volumes:
   #   - ./db:/docker-entrypoint-initdb.d/:ro
